-- ====================================================================
-- F&B PLATFORM - ML FEATURE STORE
-- Schema for storing features calculated by PySpark (Data Lake)
-- ====================================================================

CREATE SCHEMA IF NOT EXISTS ml;

DROP TABLE IF EXISTS ml.ml_features CASCADE;

CREATE TABLE ml.ml_features (
    id SERIAL PRIMARY KEY,
    branch_id INT NOT NULL REFERENCES oltp.branches(id) ON DELETE CASCADE,
    product_id INT NOT NULL REFERENCES oltp.products(id) ON DELETE CASCADE,
    feature_date DATE NOT NULL,
    
    -- Rolling calculations generated by Spark Window Functions
    rolling_7d_sales NUMERIC(10, 2),
    
    -- Trends
    popularity_trend_score FLOAT,
    branch_demand_index FLOAT,
    
    created_at TIMESTAMP DEFAULT NOW(),
    
    -- Enforce idempotency for daily batch inserts
    UNIQUE(branch_id, product_id, feature_date)
);

CREATE INDEX idx_ml_features_date ON ml.ml_features(feature_date);
CREATE INDEX idx_ml_features_branch_product ON ml.ml_features(branch_id, product_id);
